docs/README.md
docs/react_routes.md

Front-end components and react routes

docs: add docs

---

client/src/App.jsx
client/src/style.css

feat: adding bootstrap css
We need this to be added so the bootstrap library style works

bootstrap css

---

client/src/Components/Footer/index.jsx
client/src/Components/Footer/style.css

add footer text and icons and their styles
relates #16

Footer component

---

client/src/Components/Login/index.jsx
client/src/Components/Login/style.css

related to #18 
Optional notes

create login page

---

client/src/Components/MyApplications/index.jsx
client/src/Components/MyApplications/style.css
client/src/Components/utils/myApplications.js
client/src/style.css

related to #28
My Applications page will show my applications cards, It uses offers card and pass my application data to it.
hint: new styling class is added to main app style 'page__container', just add it to any main page container.
Optional notes

My applications page

---

client/src/Components/OfferDetails/ApplicationCard/index.jsx
client/src/Components/OfferDetails/ApplicationCard/style.css
client/src/Components/OfferDetails/SideCard/index.jsx
client/src/Components/OfferDetails/SideCard/style.css
client/src/Components/OfferDetails/index.jsx
client/src/Components/OfferDetails/style.css
client/src/Components/utils/applications.js
client/src/Components/utils/offer.js

related to #22
OfferDetails Page that contains all offer details
logic for application card:
- if the applicant is not hired, show hire me button
- if the application hire request is send, show 'hired request send' text.
- if the applicant accepted the hire request, show 'accepted'
- if the applicant refused the hire request, show 'refused'
- if the applicant did not post his proposal yet, show input form to submit his proposal.
- if the applicant posted his proposal, show his proposal and:
- if the offer owner did not send hire request, show pending.
- if the offer owner sent hire request, show accept or refuse buttons and the application status becomes accepted or refused.
Optional notes
- - [ ] All existing and …

Offer details

---

server/controllers/applications/getMyApplications.js
server/controllers/applications/index.js
server/routes/index.js

related to #82
add 
- getMyApplications: all member applications for all offers.
- getMyApplication: member application for specific offer.
Optional notes

Back end routes

---

server/database/config/db_build.sql
server/database/config/db_fakeData.sql

Edit schema

---

package-lock.json
package.json
server/controllers/applications/getMyApplication.js
server/controllers/applications/getMyApplications.js
server/database/queries/applications/getMyApplication.js
server/database/queries/applications/getMyApplications.js
server/database/queries/applications/index.js
test/getMyApplication.js
test/getMyApplications.js
test/index.js

related to #41
Add getMyApplication(s) route:
- If offerId is submitted it will return myApplication submitted to specific offer.
- If offerId is not subnitted, it will return all myApplications submitted (for all offers)
Optional notes

Get my applications route

---

.travis.yml
server/controllers/offer/getOffers.js
server/database/config/db_fakeData.sql
server/database/queries/offers/index.js
test/getOffersRoute.js
test/index.js

related to #58 
- query ```getOffers``` for get offers with its ```skills``` & ```offer_types```.
- route  ```/api/v1/offers/100``` for get offers.
-  ```git fetch origin get-offers```
-  ```git checkout get-offer```
-  ```git pull origin get-offer```
- ```npm run dev```
- on postman run this route ```/api/v1/offers/100```
- - [x] Console.log is only used for crucial …

Get offers

---

package.json
server/controllers/errors/index.js

related to #91 
* make error middleware the catch errors that we passing to it we have an error in any route(controller)
*  make a switch to cover error status that we may face it in our project 

Error middleware

---

server/controllers/skills/getMemberskills.js
server/database/queries/members/index.js
test/getMemberSkills.js
test/index.js

related to #45 
- query ```getMemberSkills``` for get skills of member by memberId
- route  ```/api/v1/skills/:memberId``` for get memberSkills.
-  ```git fetch origin get-member-skills```
-  ```git checkout get-member-skills```
-  ```git pull origin get-member-skills```
- ```npm run dev```
- on postman run this route ```/api/v1/skills/:memberId```
- - [x] Console.log is …

Get member skills

---

server/controllers/applications/getOfferApplication.js
server/database/queries/applications/getOfferApplications.js
server/database/queries/applications/index.js
test/getOfferApplications.js
test/index.js

related to #43 
getOfferApplication should query database for applications related to specific offerId and then return the result to client 
Optional notes

Get offer applications

---

server/controllers/skills/addSkills.js
server/database/config/db_fakeData.sql
server/database/queries/skills/index.js
server/helpers/validation-schema.js
test/index.js
test/postSkill.js

related to #48 
- query ```checkSkills``` for ensuring that is a new skill.
- query ```insertSkills``` for add new skill.
- route  ```/api/v1/skills```  with method post 
-  ```git fetch origin post-skills```
-  ```git checkout post-skills```
-  ```git pull origin  post-skills```
- ```npm run dev```
- on postman run this route  ``` `/api/v1/skills  ``` with method ` post ` 
and body    :
```javascript
{
"id": 1,
"name": "JAVAFX"
}
```
- - [x] Naming of files …

Post skills

---

client/src/Components/CommonComponents/AutoCompleteTags/index.jsx

related to #20 
shape to using the `AutoCompleteTags` Component in home 
```javascript 
<AutoCompleteTags
type="offer_type"
placeholder="eg:  fixed price
onchange={this.handleOfferTypes}
allowNew={false}
/>
```
And For add new Offer 
```javascript
<AutoCompleteTags
type="offer_type"
placeholder="eg:  fixed price
onchange={this.handleOfferTypes}
allowNew
/>
```
Optional notes
- - [ ] Console.log is only used for crucial system messages (e.g. …

AutoCompleteTags component

---

server/controllers/skills/getSkills.js
server/database/config/db_fakeData.sql
server/database/queries/skills/index.js
test/getSkills.js
test/index.js

related to #47 
- query ```getSkills``` to get all skills.
- route  ```/api/v1/skills```  with method ```GET``` 
-  ```git fetch origin get-skills```
-  ```git checkout get-skills```
-  ```git pull origin get-skills```
- ```npm run dev```
- on postman run this route  ``` `/api/v1/skills  ``` with method ` GET ` 
- - [x] Console.log is only used for crucial system messages …

Get skills

---

server/controllers/applications/addApplication.js
server/database/queries/applications/addApplication.js
server/database/queries/applications/index.js
test/addApplication.js
test/index.js

related to #51
Add new Application record to database, this accepts application data from client and post it to database then return the inserted data back to client.
note: validation and testing is also included in this PR
Optional notes
- [ x ] **Branch is up to date with master**
- [ x ] **The project runs**
- - [ x ] You can download and install locally, and run the project locally
- - [ x ] All existing and new features run without bugs
- - [ x ] The build script runs without error
- [ x ] **Code is consistent**
- - [ x ] Linter is used, no error messages
- - [ x ] Code is consistent with agreed team style
- - [ x ] Naming of files is consistent with project (e.g. all files named with camelCase)
- [ x ] **No console logs**
- - [ x ] Console.log is only used for crucial system …

Post application

---

server/controllers/offer/deleteSavedOffer.js
server/database/queries/offers/deleteSavedOffer.js
test/deleteSavedOffer.js
test/index.js

related to #60 
- query ```  deleteSavedOffer ``` for deleting the saved offer
-  ```git fetch origin delete-saved-offer ```
-  ```git checkout   delete-saved-offer```
-  ```git pull origin    delete-saved-offer ```
- ```npm run server```
- on postman run this route ``` `/api/v1/saved-offers/1  ``` with method ` POST ` 
and body    :
```javascript
{
offerId: 2
}
```
- - [ …

Delete : saved offer

---

server/controllers/authentication/logout.js
test/index.js
test/logout-controller.js

related to #42
- route  ```/api/v1/logour ```  with method `GET` 
- integration test for the route
-  ```git fetch origin logout-controller```
-  ```git checkout   logout-controller```
-  ```git pull origin  logout-controller```
- ```npm run test```

Logout controller

---

package-lock.json
package.json
server/controllers/errors/index.js
test/addMember.js

Edit the Error Middleware response to suit with other responses 
like 
```js
{ 
error : { code : 404 , msg : 'page not found ' } , data: null 
} 
```

Update Error Moddleware

---

server/controllers/authentication/index.js
server/controllers/authentication/isAuthenticated.js
server/database/queries/members/addMember.js
server/routes/index.js

related to #123
make isAthenticated route and functionality
Optional notes

Back end auth

---

server/controllers/applications/addApplication.js
test/addApplication.js

Backend | Add new application

---

client/src/Components/CommonComponents/OfferCard/index.jsx
server/controllers/offer/addSavedOffer.js
server/controllers/offer/deleteSavedOffer.js

Offer card

---

server/controllers/applications/addHiredMember.js
server/database/config/db_build.sql
server/database/queries/applications/addHiredMember.js
test/addHiredMember.js

Backend |  hiered_member route.

---

docs/backend-routes.md

Edit the back-end documentation

---

client/src/Components/MyOffers/index.jsx
server/routes/index.js

My offers page

---

server/controllers/member/addMember.js
server/routes/index.js

#131 
get data from the fetch
Optional notes

Signup back

---

client/src/Components/MyApplications/index.jsx
server/controllers/offer/getSavedOffers.js
server/database/queries/applications/getMyApplications.js
server/routes/index.js
test/getMyApplications.js

related to #28
get My Applications and show them on client
Optional notes
- [ x ] **Branch is up to date with master**
- [ x ] **The project runs**
- [ x ] **Code is consistent**
- [ x ] **No console logs**

My applications page combine

---

client/src/Components/CommonComponents/OfferCard/index.jsx
client/src/Components/SavedOffers/index.jsx
server/database/queries/offers/getSavedOffer.js

related to #30 
combine frontend with backend to show saved offers.
Optional notes
- [ x ] **Branch is up to date with master**
- [ x ] **The project runs**
- [ x ] **Code is consistent**
- [ x ] **No console logs**

Saved offer combine

---

client/src/Components/CommonComponents/OfferCard/index.jsx

fix: saved offers page

---

client/src/Components/Login/index.jsx
client/src/Components/Login/style.css

#68 
style for login
Optional notes

Login style

---

client/public/index.html
client/src/Components/LandingPage/Cards/index.jsx
client/src/Components/LandingPage/Cards/style.css
client/src/Components/LandingPage/Slider/style.css
client/src/Components/LandingPage/index.jsx
client/src/Components/LandingPage/style.css

Style landing page

---

client/src/Components/MyApplications/index.jsx
client/src/Components/MyApplications/style.css
client/src/Components/Signup/index.jsx
client/src/Components/Signup/style.css

Signup style

---

client/src/Components/OfferDetails/ApplicationCard/style.css
client/src/Components/OfferDetails/CoverLetter/index.jsx
client/src/Components/OfferDetails/CoverLetter/style.css
client/src/Components/OfferDetails/SideCard/index.jsx
client/src/Components/OfferDetails/SideCard/style.css
client/src/Components/OfferDetails/index.jsx
client/src/Components/OfferDetails/style.css

Offer deatails style

---

client/src/Components/MyOffers/style.css

My offers style

---

client/src/Components/Header/index.jsx
client/src/Components/Header/style.css

Header style

---

client/src/Components/CommonComponents/AutoCompleteTags/style.css
client/src/Components/CreateOffer/style.css

Create offer style

---

client/src/Components/MyOffers/index.jsx
client/src/Components/Signup/index.jsx

fix: store correct data on local storage
Optional notes

Fix bug: correct localStorage info

---

client/src/Components/CommonComponents/PageTitle/index.jsx
client/src/Components/CommonComponents/PageTitle/style.css
client/src/Components/CreateOffer/index.jsx
client/src/Components/CreateOffer/style.css
client/src/Components/MyApplications/index.jsx
client/src/Components/MyApplications/style.css
client/src/Components/MyOffers/index.jsx
client/src/Components/SavedOffers/index.jsx

- make new component ```PageTitle``` for pages titles.

style: new component for pages titles

---

client/package-lock.json
client/src/App.jsx
client/src/style.css

Edit style of body

---

client/src/Components/Footer/style.css

Fix footer

---

client/src/Components/Home/Members/index.jsx

Profile front end

---

client/src/Components/Home/Members/index.jsx
client/src/Components/Home/Members/style.css

Member style

---

client/src/Components/OfferDetails/ApplicationCard/index.jsx
client/src/Components/OfferDetails/ApplicationCard/style.css
client/src/Components/OfferDetails/index.jsx

Fixbug app card

---

client/src/Components/Profile/SideProfile/style.css

Profile style

---

client/src/App.jsx
client/src/auth/auth.js
server/controllers/authentication/isAuthenticated.js

related to #183 
resolve error when any member remove userInfo from localstorage
Optional notes

Login signup bugs

---

client/src/Components/OfferDetails/ApplicationCard/index.jsx

fix bug of application data
Optional notes

Application data

---

client/src/Components/LandingPage/index.jsx
client/src/Components/LandingPage/style.css

#189 
fix the style in landing page
Optional notes

Landing page style

---

client/src/Components/CommonComponents/AutoCompleteTags/style.css
client/src/Components/CommonComponents/OfferCard/index.jsx
client/src/Components/CommonComponents/OfferCard/style.css
client/src/Components/Home/Members/style.css
client/src/Components/Home/style.css

Fix home style

---

client/src/Components/CreateOffer/index.jsx

#192 
delete the error message when input again
Optional notes

New offer fix bug

---

client/src/Components/MyOffers/index.jsx
client/src/Components/MyOffers/style.css

related to #180 
Style the paragraph if there aren't offers.
Optional notes

My offer empty

---

client/src/Components/PageNotFound/index.jsx
client/src/Components/PageNotFound/style.css

edit page not found style

---

client/src/Components/Header/Notification/index.jsx

related to #203
add a message if the notification is empty.
Optional notes

Notification style

---

client/src/Components/CreateOffer/index.jsx
client/src/Components/CreateOffer/style.css

related to #182 
made style more responsive
Optional notes

New offer style

---

client/src/Components/CommonComponents/PageTitle/index.jsx
client/src/Components/CommonComponents/PageTitle/style.css
client/src/Components/Header/style.css

related to #194 
Optional notes

Header and public pages

---

client/src/Components/Profile/MemberInfo/Education/index.jsx
client/src/Components/Profile/MemberInfo/Experience/index.jsx

Refactor Profile 

---

client/src/Components/CommonComponents/OfferCard/index.jsx
client/src/Components/CommonComponents/OfferCard/style.css
client/src/index.js

fix: fix fontawesome and saved bookmark style

---

client/src/Components/MyOffers/index.jsx

Fix my offers escape key down

---

client/src/Components/Footer/style.css
client/src/Components/Header/index.jsx
client/src/Components/Header/style.css

Fix header and footer

---

client/src/Components/CommonComponents/OfferCard/style.css
client/src/Components/Header/style.css
client/src/Components/Home/Members/index.jsx
client/src/Components/Home/Members/style.css
client/src/Components/OfferDetails/CoverLetter/index.jsx
client/src/Components/OfferDetails/CoverLetter/style.css
client/src/style.css

Members name style

---

client/src/Components/Header/Notification/index.jsx
client/src/Components/Header/Notification/style.css
server/controllers/applications/addApplication.js

Fix notification number

---

client/src/Components/OfferDetails/ApplicationCard/index.jsx

fix-bug: take user information from auth not localStorage

Application card
